consultorio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('entidades.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

entidades/urls.py
from django.urls import path, include
from entidades.views import * 
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', home, name="home"),
    
    path('citas/', citas, name="citas"),
    #path('fichas/', citas, name="fichas"),
    
    #__especialidades__#
    path('especialidades/', especialidades, name="especialidades"),
    path('especialidadForm/', especialidadForm, name="especialidadForm"),
    path('buscarEspecialidad/', buscarEspecialidad, name="buscarEspecialidad"),
    path('encontrarEspecialidad/', encontrarEspecialidad, name="encontrarEspecialidad"),
    path('especialidadUpdate/<id_especialidad>/', especialidadUpdate, name="especialidadUpdate"),
    path('especialidadDelete/<id_especialidad>/', especialidadDelete, name="especialidadDelete"),
    
    #__doctores__#
    path('doctores/', doctores, name="doctores"),
    path('doctorForm/', doctorForm, name="doctorForm"),
    path('buscarDoctor/', buscarDoctor, name="buscarDoctor"),
    path('encontrarDoctor/', encontrarDoctor, name="encontrarDoctor"),
    path('doctorUpdate/<id_doctor>/', doctorUpdate, name="doctorUpdate"),
    path('doctorDelete/<id_doctor>/', doctorDelete, name="doctorDelete"),

    #__Fichas__#
    path('ficha/', FichaList.as_view(), name="ficha"),
    path('fichaCreate/', FichaCreate.as_view(), name="fichaCreate"),
    path('fichaUpdate/<int:pk>', FichaUpdate.as_view(), name="fichaUpdate"),
    path('fichaDelete/<int:pk>', FichaDelete.as_view(), name="fichaDelete"),

    #__Citas__#
    path('cita/', CitaList.as_view(), name="cita"),
    path('citaCreate/', CitaCreate.as_view(), name="citaCreate"),
    path('citaUpdate/<int:pk>', CitaUpdate.as_view(), name="citaUpdate"),
    path('citaDelete/<int:pk>', CitaDelete.as_view(), name="citaDelete"),

    #__Login Logout register__#
    path('login/', loginRequest, name="login"),
    path('logout/', LogoutView.as_view(template_name="entidades/logout.html"), name="logout"),
    path('registro/', register, name="registro"),

    #__Edicion perfil y avatar__#
     path('perfil/', editProfile, name="perfil"),
     path('<int:pk>/password/', cambiarClave.as_view(), name="cambiarClave"),
     path('agregar_avatar/', agregarAvatar, name='agregarAvatar'),

    #__AcercaDe__#
    path('acercaDe/', acercaDe, name="acercaDe"),

]

entidades/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Especialidad(models.Model):
    nombre = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.nombre}"
    
    ordering = ["nombre"]
    
    class Meta:
        verbose_name = "Especialidad"
        verbose_name_plural = "Especialidades"
 
class Doctor(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.apellido},   {self.nombre}"
    
    class Meta:
        verbose_name = "Doctor"
        verbose_name_plural = "Doctores"
        ordering = ["nombre", "apellido"]

class Paciente(models.Model):
    nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.apellido},   {self.nombre}"

class Cita(models.Model):
    fecha = models.DateField()
    paciente = models.IntegerField()
    doctor = models.IntegerField()
    
class Ficha(models.Model):
    cita = models.IntegerField()
    diagnostico = models.TextField()
    receta = models.TextField()

    def __str__(self):
        return f"{self.cita},   {self.diagnostico}, {self.receta} "

class Avatar(models.Model):
    imagen = models.ImageField(upload_to="avatares")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} {self.imagen}"

entidades/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class EspecialidadForm(forms.Form):
    nombre = forms.CharField(max_length=100, required=True)
    
class DoctorForm(forms.Form):
    nombre = forms.CharField(max_length=100, required=True)
    apellido = forms.CharField(max_length=100, required=True)
    email = forms.CharField(max_length=100, required=True)
    
    
class CitaForm(forms.Form):
    nombre = forms.CharField(max_length=100, required=True)

class RegistroForm(UserCreationForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmar Contraseña", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ["username","email","password1","password2"]

class UserEditForm(UserChangeForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(label="Nombre", max_length=100, required=True)
    last_name = forms.CharField(label="Apellido", max_length=100, required=True)

    class Meta:
        model = User
        fields = ["email","first_name","last_name"]

class AvatarForm(forms.Form):
    imagen = forms.ImageField(required=True)

entidades/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import *
from .forms import *
from django.views.generic import ListView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView

from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import PasswordChangeView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .forms import UserEditForm


# Create your views here.
def home(request):
    return render(request, "entidades/index.html")

def citas(request):
    contexto = {"citas": Cita.objects.all()}
    return render(request, "entidades/citas.html")

#__Especialidad__#

@login_required
def especialidades(request):
    contexto = {"especialidades": Especialidad.objects.all()}
    return render(request, "entidades/especialidades.html", contexto)

@login_required
def especialidadForm(request):
    if request.method == "POST":
        miForm = EspecialidadForm(request.POST)
        if miForm.is_valid():
            especialidad_nombre = miForm.cleaned_data.get("nombre")
            especialidad = Especialidad(nombre=especialidad_nombre)
            especialidad.save()
            contexto = {"especialidades": Especialidad.objects.all()}
            return render(request, "entidades/especialidades.html", contexto)
    else:
        miForm = EspecialidadForm()
        return render(request, "entidades/especialidadForm.html", {"form": miForm})

@login_required    
def buscarEspecialidad(request):
    return render(request, "entidades/buscarEspecialidad.html")

@login_required
def encontrarEspecialidad(request):
    if request.GET["buscar"]:
        patron = request.GET["buscar"]
        especialidades = Especialidad.objects.filter(nombre__icontains=patron)
        contexto = {'especialidades': especialidades}
    else:
        contexto = {'especialidades': Especialidad.objects.all()}
        
    return render(request, "entidades/especialidades.html", contexto)

@login_required
def especialidadUpdate(request,id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    if request.method == "POST":
        miForm = EspecialidadForm(request.POST)
        if miForm.is_valid():
            especialidad.nombre = miForm.cleaned_data.get("nombre")
            especialidad.save()
            contexto = {"especialidades": Especialidad.objects.all()}
            return render(request, "entidades/especialidades.html", contexto)
    else:
        miForm = EspecialidadForm(initial={"nombre": especialidad.nombre,})
        return render(request, "entidades/especialidadForm.html", {"form": miForm})

@login_required    
def especialidadDelete(request,id_especialidad):
    especialidad = Especialidad.objects.get(id=id_especialidad)
    especialidad.delete()
    contexto = {"especialidades": Especialidad.objects.all()}
    return render(request, "entidades/especialidades.html", contexto)

#__Doctor__#
@login_required
def doctores(request):
    contexto = {"doctores": Doctor.objects.all()}
    return render(request, "entidades/doctores.html", contexto)

@login_required
def doctorForm(request):
    if request.method == "POST":
        miForm = DoctorForm(request.POST)
        if miForm.is_valid():
            doctor_nombre = miForm.cleaned_data.get("nombre")
            doctor_apellido = miForm.cleaned_data.get("apellido")
            doctor_email = miForm.cleaned_data.get("email")
            doctor = Doctor(nombre=doctor_nombre,apellido=doctor_apellido,email=doctor_email)
            doctor.save()
            contexto = {"doctores": Doctor.objects.all()}
            return render(request, "entidades/doctores.html", contexto)
    else:
        miForm = DoctorForm()
        return render(request, "entidades/doctorForm.html", {"form": miForm}) 
    
@login_required
def buscarDoctor(request):
    return render(request, "entidades/buscarDoctor.html")

@login_required
def encontrarDoctor(request):
    if request.GET["buscar"]:
        patron = request.GET["buscar"]
        doctores = Doctor.objects.filter(nombre__icontains=patron)
        contexto = {'doctores': doctores}
    else:
        contexto = {'doctores': Doctor.objects.all()}
        
    return render(request, "entidades/doctores.html", contexto)

@login_required
def doctorUpdate(request,id_doctor):
    doctor = Doctor.objects.get(id=id_doctor)
    if request.method == "POST":
        miForm = DoctorForm(request.POST)
        if miForm.is_valid():
            doctor.nombre = miForm.cleaned_data.get("nombre")
            doctor.apellido = miForm.cleaned_data.get("apellido")
            doctor.email = miForm.cleaned_data.get("email")
            doctor.save()
            contexto = {"doctores": Doctor.objects.all()}
            return render(request, "entidades/doctores.html", contexto)
    else:
        miForm = DoctorForm(initial={"nombre": doctor.nombre, "apellido": doctor.apellido, "email": doctor.email})
        return render(request, "entidades/doctorForm.html", {"form": miForm})

@login_required    
def doctorDelete(request,id_doctor):
    doctor = Doctor.objects.get(id=id_doctor)
    doctor.delete()
    contexto = {"doctores": Doctor.objects.all()}
    return render(request, "entidades/doctores.html", contexto)

#__ficha__#

class FichaList(ListView,LoginRequiredMixin):
    model = Ficha

class FichaCreate(CreateView,LoginRequiredMixin):
    model = Ficha
    fields = ["cita","diagnostico","receta"]
    success_url = reverse_lazy("ficha")

class FichaUpdate(UpdateView,LoginRequiredMixin):
    model = Ficha
    fields = ["cita","diagnostico","receta"]
    success_url = reverse_lazy("ficha")

class FichaDelete(DeleteView,LoginRequiredMixin):
    model = Ficha
    success_url = reverse_lazy("ficha")

#__Cita__#

class CitaList(ListView,LoginRequiredMixin):
    model = Cita

class CitaCreate(CreateView,LoginRequiredMixin):
    model = Cita
    fields = ["fecha","paciente","doctor"]
    success_url = reverse_lazy("cita")

class CitaUpdate(UpdateView,LoginRequiredMixin):
    model = Cita
    fields = ["cita","diagnostico","receta"]
    success_url = reverse_lazy("cita")

class CitaDelete(DeleteView,LoginRequiredMixin):
    model = Cita
    success_url = reverse_lazy("cita")

#__Login Logout register__#

def loginRequest(request):
    if request.method == ("POST"):
        usuario = request.POST["username"]
        clave = request.POST["password"]
        user = authenticate(request, username=usuario, password=clave)
        if user is not None:
            login(request, user)

            try:
                avatar = Avatar.objects.get(user=request.user.id).imagen.url
            except:
                avatar = "/media/avatares/default.png"
            finally:
                request.session["avatar"] = avatar

            return render(request, "entidades/index.html")
        else:
            return redirect(reverse_lazy('login'))
    else:
        miForm = AuthenticationForm()

    return render(request, "entidades/login.html", {"form": miForm})

def register(request):
    if request.method == ("POST"):
        miForm = RegistroForm(request.POST)
        if miForm.is_valid():
            miForm.save()
            return redirect(reverse_lazy('home'))
    else:
        miForm = RegistroForm()

    return render(request, "entidades/registro.html", {"form": miForm})

#___Edicion de perfil y avatar__#

@login_required
def editProfile(request):
    user = request.user

    if request.method == "POST":
        miForm = UserEditForm(request.POST, instance=user)
        if miForm.is_valid():
            miForm.save()
            return redirect(reverse_lazy("home"))
    else:
        miForm = UserEditForm(instance=user)
    return render(request, "entidades/editarPerfil.html", {"form": miForm})

class cambiarClave(LoginRequiredMixin,PasswordChangeView):
    template_name = "entidades/cambiar_clave.html"
    success_url = reverse_lazy("home")

@login_required
def agregarAvatar(request):
    if request.method == "POST":
        miForm = AvatarForm(request.POST, request.FILES)
        if miForm.is_valid():
            usuario = User.objects.get(username=request.user)
            imagen = miForm.cleaned_data["imagen"]
            #borrar avatar viejo
            avatarViejo = Avatar.objects.filter(user=usuario)
            if len(avatarViejo)>0:
                for i in range(len(avatarViejo)):
                    avatarViejo[i].delete()
            avatar = Avatar(user=usuario, imagen=imagen)
            avatar.save()

            #enviar imagen al home
            imagen = Avatar.objects.get(user=usuario).imagen.url
            request.session["avatar"] = imagen
            return redirect(reverse_lazy("home"))
    else:
        miForm = AvatarForm()
    return render(request, "entidades/agregarAvatar.html", {"form": miForm})

def acercaDe(request):
    return render(request, "entidades/acercaDe.html")

entidades/templates/entidades/acercaDe.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Acerca De</h1>
{% endblock titulo %}


{% block contenido %}
<div style="text-center">
    <p>Nombre del alumno: Ronald Alfonzo</p>
    <p>Profesión: Ing. Informatico.</p>
    <p>Nacionalidad: Venezolana</p>
    <p>Edad: 36</p>
    <p>Fecha de nacimiento: 7 diciembre 1987</p>
    <p>País de residencia: Chile</p>
</div>

{% endblock contenido %}

entidades/templates/entidades/agregarAvatar.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Avatar</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}

<table>
    {{ form.as_table }}
</table>
<input type="submit" value="Actualizar">
</form>

{% endblock contenido %}

entidades/templates/entidades/cambiar_clave.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Cambiar Contraseña</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="post">
{% csrf_token %}

<table>
    {{ form.as_table }}
</table>
<input type="submit" value="Cambiar clve">
</form>

{% endblock contenido %}

entidades/templates/entidades/cita_confirm_delete.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Eliminar Ficha</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="POST">
{% csrf_token %}
<div class="text-center">
    <h3>¿Estas seguro de eliminar el registro?<p style="color:red">{{ object }}</p>
    </div>
    <div class="text-center">
        <input type="submit" class="btn btn-primary btn-block" value="Confirmar">   <a class="btn btn-primary btn-block" href="{% url 'ficha' %}">Cancelar</a>
    </div>
</form>
{% endblock contenido %}

entidades/templates/entidades/cita_form.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1 class="masthead-subheading font-weight-light mb-0">Agregar Cita</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="post">
    <div class="form-group">
    {% csrf_token %}
    <table>
        <br>
        {{ form.as_table }}
    </table>
    <br>
    <input class="btn btn-primary btn-block" type="submit" value="Guardar">
</div>
</form>
{% endblock contenido %}

entidades/templates/entidades/citas.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Citas Medicas</h1>
{% endblock titulo %}


{% block contenido %}
<table>
    <tr>
        <td width="200"><h2>Agregar</h2></td>
        <td>
            <a href="{% url 'citaCreate' %}"
            class="btn btn-primary btn-sm"><i class="fa fa-plus fa-lg" title="Crear"></i>
            </a>
        </td>
    </tr>    
</table>

<table class="table table-striped">
    <thead>
        <tr>
            <th>id</th>
            <th>Fecha</th>
            <th>Paciente</th>
            <th>Doctor</th>
        </tr>
    </thead>
    <tbody>
        {% for cita in cita_list %}
            <tr>
                <td>{{ cita.id }}</td>
                <td>{{ cita.fecha }}</td>
                <td>{{ cita.paciente }}</td>
                <td>{{ cita.doctor }}</td>
                <td>
                    <a
                      href="{% url 'citaUpdate' cita.id %}"
                      class="btn btn-primary"
                      style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                      ><i class="fa fa-edit fa-sm" title="Editar"></i>
                    </a>
                    <a
                      href="{% url 'citaDelete' cita.id %}"
                      class="btn btn-danger"
                      style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                      ><i class="fa fa-trash fa-sm" title="Eliminar"></i>
                    </a>                
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

entidades/templates/entidades/doctorForm.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1 class="masthead-subheading font-weight-light mb-0">Agregar Doctores</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="post">
    <div class="form-group">
    {% csrf_token %}
    <table>
        <br>
        {{ form }}
    </table>
    <br>
    <input class="btn btn-primary btn-block" type="submit" value="Guardar">
</div>
</form>
{% endblock contenido %}

entidades/templates/entidades/especialidadForm.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1 class="masthead-subheading font-weight-light mb-0">Agregar Especialidades</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        <br>
        {{ form }}
    </table>
    <br>
    <input class="btn btn-primary btn-block" type="submit" value="Guardar">
</form>
{% endblock contenido %}

entidades/templates/entidades/especialidades.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1 class="masthead-subheading font-weight-light mb-0">Especialidades</h1>
{% endblock titulo %}


{% block contenido %}

<form action="{% url 'encontrarEspecialidad' %}" method="get">
    <div class="form-group">
    {% csrf_token %}
    <table>
        <br>
        <p>Buscar Especialidad: <input type="Text" name="buscar" id="buscar"> <input class="btn btn-primary btn-sm" type="submit" value="Buscar">
    </table>
    
</div>
</form>

<table>
    <tr>
        <td width="200"><h3>Agregar</h3></td>
        <td>
            <a href="{% url 'especialidadForm' %}"
            class="btn btn-primary btn-sm"><i class="fa fa-plus fa-lg" title="Crear"></i>
            </a>
        </td>
    </tr>    
</table>

<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Nombre especialidad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for especialidad in especialidades %}
            <tr>
                <td>{{ especialidad.id }}</td>
                <td>{{ especialidad.nombre }}</td>
                <td>
                    <a
                      href="{% url 'especialidadUpdate' especialidad.id %}"
                      class="btn btn-primary"
                      style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                      ><i class="fa fa-edit fa-sm" title="Editar"></i>
                    </a>
                    <a
                      href="{% url 'especialidadDelete' especialidad.id %}"
                      class="btn btn-danger"
                      style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                      ><i class="fa fa-trash fa-sm" title="Eliminar"></i>
                    </a>                
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

entidades/templates/entidades/ficha_confirm_delete.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Eliminar Ficha</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="POST">
{% csrf_token %}
<div class="text-center">
    <h3>¿Estas seguro de eliminar el registro?<p style="color:red">{{ object }}</p>
    </div>
    <div class="text-center">
        <input type="submit" class="btn btn-primary btn-block" value="Confirmar">   <a class="btn btn-primary btn-block" href="{% url 'ficha' %}">Cancelar</a>
    </div>
</form>
{% endblock contenido %}

entidades/templates/entidades/ficha_form.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1 class="masthead-subheading font-weight-light mb-0">Agregar Ficha</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="post">
    <div class="form-group">
    {% csrf_token %}
    <table>
        <br>
        {{ form.as_table }}
    </table>
    <br>
    <input class="btn btn-primary btn-block" type="submit" value="Guardar">
</div>
</form>
{% endblock contenido %}

entidades/templates/entidades/ficha_list.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Fichas Medicas</h1>
{% endblock titulo %}


{% block contenido %}
<table>
    <tr>
        <td width="200"><h2>Agregar</h2></td>
        <td>
            <a href="{% url 'fichaCreate' %}"
            class="btn btn-primary btn-sm"><i class="fa fa-plus fa-lg" title="Crear"></i>
            </a>
        </td>
    </tr>    
</table>

<table class="table table-striped">
    <thead>
        <tr>
            <th>id</th>
            <th>Cita</th>
            <th>Diagnostico</th>
            <th>Receta</th>
        </tr>
    </thead>
    <tbody>
        {% for ficha in ficha_list %}
            <tr>
                <td>{{ ficha.id }}</td>
                <td>{{ ficha.cita }}</td>
                <td>{{ ficha.diagnostico }}</td>
                <td>{{ ficha.receta }}</td>
                <td>
                    <a
                      href="{% url 'fichaUpdate' ficha.id %}"
                      class="btn btn-primary"
                      style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                      ><i class="fa fa-edit fa-sm" title="Editar"></i>
                    </a>
                    <a
                      href="{% url 'fichaDelete' ficha.id %}"
                      class="btn btn-danger"
                      style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;"
                      ><i class="fa fa-trash fa-sm" title="Eliminar"></i>
                    </a>                
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

entidades/templates/entidades/login.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Login</h1>
{% endblock titulo %}


{% block contenido %}

<form action="" method="post">
{% csrf_token %}

<table>
    {{ form.as_table }}
</table>
<input type="submit" value="Login">
</form>

{% endblock contenido %}

entidades/templates/entidades/logout.html
{% extends 'entidades/index.html' %}


{% block titulo %}
<h1>Logout</h1>
{% endblock titulo %}


{% block contenido %}

<h4>
    <p style="color:red" align="center">Se ha cerrado la sesión con exito.</p>
</h4>

{% endblock contenido %}